name: esgotoserver
version: '1.0'
main: org.esg.Main
depend: [NBTAPI]

commands:
  heal:
    description: Cura o jogador
    usage: /<command>
  guns:
    description: Abre o menu de armas
    usage: /<command>
