name: Move Assigned Issue to In Progress

on:
  issues:
    types: [assigned]

jobs:
  move-to-in-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to "Em progresso"
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} 
          PROJECT_ID: "PVT_kwHOB_7ta84Az5-l"
          COLUMN_NAME: "Em progresso"
        run: |
          gh api graphql -F projectId="$PROJECT_ID" -F contentId="${{ github.event.issue.node_id }}" -F columnName="$COLUMN_NAME" -f query='
          mutation($projectId: ID!, $contentId: ID!, $columnName: String!) {
            addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
              item {
                id
              }
            }
          }'
